name = "swarm-fm-uptime-worker"
main = "src/index.ts"
compatibility_date = "2025-04-25"

[vars]
NODE_VERSION = "22.14.0"
PNPM_VERSION = "10.8.0"

# Durable Objects
[durable_objects]
bindings = [
  { name = "LIVE_DO", class_name = "LiveStatusDO" }
]

[triggers]
# Define cron schedules for triggering the worker
crons = ["*/1 * * * *"]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "LiveStatusDO" ]

[observability.logs]
enabled = true
