name = "sfm-uptime-tracker"
main = "src/index.ts"
compatibility_date = "2025-08-22"

# Workers KV namespace
[[kv_namespaces]]
binding = "SwarmFM-LiveStatusKV"
id = "78006c3e99114591a314c0c8245229bc"

[triggers]
# Define cron schedules for triggering the worker
crons = ["*/3 * * * *"]

[observability.logs]
enabled = true

# add a new migration (tag must be unique)
[[migrations]]
tag = "delete-live-status-do-2025-08-22"
deleted_classes = ["LiveStatusDO"]
