name = "swarm-fm-uptime-worker"
main = "src/index.ts"
compatibility_date = "2025-04-25"

# Durable Objects
[durable_objects]
bindings = [
  { name = "LIVE_DO", class_name = "LiveStatusDO" }
]

[triggers]
# Define cron schedules for triggering the worker
crons = ["*/3 * * * *"]

[[migrations]]
tag = "v1"
new_sqlite_classes = [ "LiveStatusDO" ]

[observability.logs]
enabled = true

[[analytics_engine_datasets]]
binding = "swarmfm_logs"
dataset = "SWARMFM_LOGS"
